# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CharacterSheet.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(200, 10, 361, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RaceLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.RaceLabel.setObjectName("RaceLabel")
        self.verticalLayout.addWidget(self.RaceLabel)
        self.RaceComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.RaceComboBox.setObjectName("RaceComboBox")
        self.verticalLayout.addWidget(self.RaceComboBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.AlignmentLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AlignmentLabel.setObjectName("AlignmentLabel")
        self.verticalLayout_4.addWidget(self.AlignmentLabel)
        self.AlignmentComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.AlignmentComboBox.setObjectName("AlignmentComboBox")
        self.verticalLayout_4.addWidget(self.AlignmentComboBox)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ClassLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ClassLabel.setObjectName("ClassLabel")
        self.verticalLayout_2.addWidget(self.ClassLabel)
        self.ClassComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.ClassComboBox.setObjectName("ClassComboBox")
        self.verticalLayout_2.addWidget(self.ClassComboBox)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.BackgroundLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.BackgroundLabel.setObjectName("BackgroundLabel")
        self.verticalLayout_3.addWidget(self.BackgroundLabel)
        self.BackgroundComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.BackgroundComboBox.setObjectName("BackgroundComboBox")
        self.verticalLayout_3.addWidget(self.BackgroundComboBox)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 160, 41))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.CharacterNameLabel = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.CharacterNameLabel.setObjectName("CharacterNameLabel")
        self.verticalLayout_5.addWidget(self.CharacterNameLabel)
        self.CharacterNameLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.CharacterNameLineEdit.setObjectName("CharacterNameLineEdit")
        self.verticalLayout_5.addWidget(self.CharacterNameLineEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RaceLabel.setText(_translate("MainWindow", "Раса"))
        self.AlignmentLabel.setText(_translate("MainWindow", "Мировозрение"))
        self.ClassLabel.setText(_translate("MainWindow", "Класс"))
        self.BackgroundLabel.setText(_translate("MainWindow", "Предыстория"))
        self.CharacterNameLabel.setText(_translate("MainWindow", "Имя персонажа"))
